using BaseLib.Abstracts;
using BaseLib.Utils;
using HermitMod.Character;
using HermitMod.Extensions;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Models;

namespace HermitMod.Cards;

/// <summary>
/// Unplayable. If this is Dead On at the end of your turn, deal 13 damage to EVERYONE.
/// Generated by Midnight card. Not in card pool.
/// </summary>
[Pool(typeof(HermitCardPool))]
public sealed class ImpendingDoom : CustomCardModel
{
    public ImpendingDoom() : base(-2, CardType.Status, CardRarity.Rare, TargetType.None) { }

    public override IEnumerable<CardKeyword> CanonicalKeywords => [CardKeyword.Unplayable];

    public override string CustomPortraitPath => "impending_doom.png".BigCardImagePath();
    public override string PortraitPath => "impending_doom.png".CardImagePath();
    public override string BetaPortraitPath => "beta/impending_doom.png".CardImagePath();

    protected override Task OnPlay(PlayerChoiceContext ctx, CardPlay play)
    {
        return Task.CompletedTask;
    }

    protected override void OnUpgrade() { }
}
